stages:
  - build


build:
  tags:
    - docker
  stage: build
  image: paglipay/naemon:latest
  # before_script:
  #   - docker login -u paglipay -p $CI_REGISTRY_PASSWORD  
  script: 
    - echo "Start building App"
    - pwd
    - ls -la
