stages:
  - build


build:
  tags:
    - docker
  stage: build
  image: python:latest
  # before_script:
  #   - docker login -u paglipay -p $CI_REGISTRY_PASSWORD  
  before_script:
    - git remote set-url origin https://root:S8Aw7r2nQWKLxbxPR-Ar@corp.paglipay.info/root/feedback-loop
    - git config --global user.email 'paglipay@gmail.com'
    - git config --global user.name 'paglipay'
  script: 
    - echo "Start building App"
    - pwd
    - ls -la
    - echo "We are currently in stage 2"
    - git checkout -B branch
    - # do the file changes here
    - echo "running python script"
    - python3 main.py
    # - git checkout master
    # - git push origin master
    - touch branch.txt
    - git add .'
    - git commit -m '[skip ci] commit from CI runner'
    - git push --follow-tags origin branch
