stages:
  - build


build:
  tags:
    - docker
  stage: build
  image: python:latest
  # before_script:
  #   - docker login -u paglipay -p $CI_REGISTRY_PASSWORD  
   before_script:
    - apt-get update -y && apt-get install -yqqf openssh-client git unzip sshpass rsync --fix-missing
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_TOOLKIT" | tr -d '\r' | ssh-add - > /dev/null

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan $GITLAB_URL >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - git config --global user.email "our@email.com"
    - git config --global user.name "Gitlab Runner"
  script: 
    - echo "Start building App"
    - pwd
    - ls -la
    - echo "We are currently in stage 2"
    - echo "running python script"
    - python3 main.py
    - git checkout master
    - git push origin master
