stages:
  - build


build:
  tags:
    - docker
  stage: build
  image: python:latest
  # before_script:
  #   - docker login -u paglipay -p $CI_REGISTRY_PASSWORD  
  script: 
    - echo "Start building App"
    - pwd
    - ls -la
    - echo "We are currently in stage 2"
    - echo "running python script"
    - python3 main.py
